# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

project_name: ovh-dyndns

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    dir: ./cmd/ovh-dyndns
    main: .
    binary: ovh-dyndns
    # Ignore combinations that don't make sense or aren't supported if necessary
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the archive name compatible with the standard
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    # use zip for windows
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

